server:
  port: ${PORT:5000}
logging:
  level:
    root: ERROR
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  application:
    name: personal
app:
  environment: test
  parameter-names:
    email-address-name: /schfme/email/connect
    api-client-key-name: "/schfme-content-api/${app.environment}/api-keys/schfme"
    api-client-base-path-name: "/schfme-content-api/${app.environment}/base-path"
    cluster-name: "/schfme/${app.environment}/database/connection/cluster-name"
    host: "/schfme/${app.environment}/database/connection/host"
    database-name: "/schfme/${app.environment}/database/name"
    service-name: "/schfme/${app.environment}/database/service/name"
    service-password: "/schfme/${app.environment}/database/service/password"
cache:
  ttl:
    recent-posts-cache: 5m
    recent-post-headlines-cache: 5m
    post-by-title-cache: 10m
site-properties:
  external-link-config:
    git-hub-link: https://github.com/schfme
    ig-link: https://www.instagram.com/schf.me
    linkedin-link: https://www.linkedin.com/in/schfme/
    resume-link: https://s3.us-east-2.amazonaws.com/assets.schf.me/resume.pdf
  rss-feed-config:
    feed-title: Updates from schf.me
    feed-description: A pause between the playing of two tunes.
    feed-version: 2.0
    max-feed-entry-count: 10
    
---
spring:
  config:
    activate:
      on-profile: test

app:
  environment: test
---
spring:
  config:
    activate:
      on-profile: prod

app:
  environment: prod
